### ISSUE TITLE
[Test] org.eclipse.jdt.debug.tests.ui.DebugViewTests fails on Windows

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#112]
https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jdt.debug.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html

testWrongSelectionBug534319lateStart | Failure | expected no assertions to fail during test expected:<[]> but was:<[junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@24032c9d expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>]>junit.framework.AssertionFailedError: expected no assertions to fail during test expected:<[]> but was:<[junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@24032c9d expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>]>at junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.failNotEquals(Assert.java:329)at junit.framework.Assert.assertEquals(Assert.java:78)at junit.framework.TestCase.assertEquals(TestCase.java:238)at org.eclipse.jdt.debug.tests.ui.AbstractDebugViewTests.doTestWrongSelection(AbstractDebugViewTests.java:133)at org.eclipse.jdt.debug.tests.ui.AbstractDebugViewTests.doTestWrongSelection(AbstractDebugViewTests.java:95)at org.eclipse.jdt.debug.tests.ui.DebugViewTests.doTestWrongSelectionBug534319(DebugViewTests.java:245)at org.eclipse.jdt.debug.tests.ui.DebugViewTests.testWrongSelectionBug534319lateStart(DebugViewTests.java:139)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2678)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:829)
-- | -- | --

testWrongSelectionBug534319startBetwen | Failure | expected no assertions to fail during test expected:<[]> but was:<[junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@20eedd83 expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>, junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@74292d81 expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>, junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@672f677a expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>]>junit.framework.AssertionFailedError: expected no assertions to fail during test expected:<[]> but was:<[junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@20eedd83 expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>, junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@74292d81 expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>, junit.framework.AssertionFailedError: Wrong object selected: org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget@672f677a expected:<class org.eclipse.jdt.internal.debug.core.model.JDIStackFrame> but was:<class org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget>]>at junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.failNotEquals(Assert.java:329)at junit.framework.Assert.assertEquals(Assert.java:78)at junit.framework.TestCase.assertEquals(TestCase.java:238)at org.eclipse.jdt.debug.tests.ui.AbstractDebugViewTests.doTestWrongSelection(AbstractDebugViewTests.java:133)at org.eclipse.jdt.debug.tests.ui.AbstractDebugViewTests.doTestWrongSelection(AbstractDebugViewTests.java:95)at org.eclipse.jdt.debug.tests.ui.DebugViewTests.doTestWrongSelectionBug534319(DebugViewTests.java:245)at org.eclipse.jdt.debug.tests.ui.DebugViewTests.testWrongSelectionBug534319startBetwen(DebugViewTests.java:147)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2678)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:829)
-- | -- | --

**Comment by jukzi** [comment]
cannot reproduce
