### ISSUE TITLE
org.eclipse.jdt.debug.tests.connectors.MultipleConnectionsTest.testTwoConnectionsBehaviour() hangs

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#122]
Initially found because Gerrit builds stuck forever, with errors like below. Can reproduce locally.

Also SDK build shows DNF in jdt.debug.tests:
https://download.eclipse.org/eclipse/downloads/drops4/I20220916-0140/testResults.php

`org.eclipse.jdt.debug.tests.connectors.MultipleConnectionsTest.testTwoConnectionsBehaviour()` test hangs on trying connect to the JVM. 
This is a regression from https://github.com/eclipse-platform/eclipse.platform/pull/169

```
13:15:11  !ENTRY org.eclipse.jdt.debug.tests 1 0 2022-09-16 11:15:11.167
13:15:11  !MESSAGE [testSingleConnectionBehaviour] setUp
13:15:11  
13:15:11  !ENTRY org.eclipse.jdt.debug 4 125 2022-09-16 11:15:11.386
13:15:11  !MESSAGE Internal error logged from JDI Debug: 
13:15:11  !STACK 0
13:15:11  com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
13:15:11  	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:93)
13:15:11  	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:190)
13:15:11  	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:230)
13:15:11  	at org.eclipse.jdi.internal.request.EventRequestImpl.enable(EventRequestImpl.java:261)
13:15:11  	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget$ThreadStartHandler.createRequest(JDIDebugTarget.java:2263)
13:15:11  	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget$ThreadStartHandler.<init>(JDIDebugTarget.java:2251)
13:15:11  	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.initializeRequests(JDIDebugTarget.java:614)
13:15:11  	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.initialize(JDIDebugTarget.java:556)
13:15:11  	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.<init>(JDIDebugTarget.java:380)
13:15:11  	at org.eclipse.jdt.debug.core.JDIDebugModel.lambda$0(JDIDebugModel.java:238)
13:15:11  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
13:15:11  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
13:15:11  	at org.eclipse.jdt.debug.core.JDIDebugModel.newDebugTarget(JDIDebugModel.java:240)
13:15:11  	at org.eclipse.jdt.debug.core.JDIDebugModel.newDebugTarget(JDIDebugModel.java:192)
13:15:11  	at org.eclipse.jdt.internal.launching.SocketListenConnectorProcess$WaitForConnectionJob.run(SocketListenConnectorProcess.java:343)
13:15:11  	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Test hangs here:
```
"main" #1 prio=6 os_prio=0 cpu=5956.09ms elapsed=480.14s tid=0x00007ffff0018000 nid=0x4842 runnable  [0x00007ffff7fc8000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(java.base@11.0.10/Native Method)
        at java.net.SocketInputStream.socketRead(java.base@11.0.10/SocketInputStream.java:115)
        at java.net.SocketInputStream.read(java.base@11.0.10/SocketInputStream.java:168)
        at java.net.SocketInputStream.read(java.base@11.0.10/SocketInputStream.java:140)
        at java.net.SocketInputStream.read(java.base@11.0.10/SocketInputStream.java:126)
        at org.eclipse.jdt.debug.tests.connectors.MultipleConnectionsTest.connect(MultipleConnectionsTest.java:156)
        at org.eclipse.jdt.debug.tests.connectors.MultipleConnectionsTest.testTwoConnectionsBehaviour(MultipleConnectionsTest.java:118)
```

**Comment by iloveeclipse** [comment]
Fixed in I20220919-0240 via https://github.com/eclipse-platform/eclipse.platform/pull/176
