### ISSUE TITLE
jdt.debug.tests DNF sporadically since I20220912-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#137]
https://download.eclipse.org/eclipse/downloads/drops4/I20220920-2240/testResults.php
https://download.eclipse.org/eclipse/downloads/drops4/I20220919-1800/testResults.php

**Comment by iloveeclipse** [comment]
In https://download.eclipse.org/eclipse/downloads/drops4/I20220925-1800/testResults.php tests DNF on ep426I-unit-macM1-java17 *and* on ep426I-unit-cen64-gtk3-java18.

Scroll down to `DumpStackTracesTimer almost reached timeout` in log files below to see stack traces.

- [org.eclipse.jdt.debug.tests.AutomatedSuite_java18_linux.txt](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/9646010/org.eclipse.jdt.debug.tests.AutomatedSuite_java18_linux.txt)
- [org.eclipse.jdt.debug.tests.AutomatedSuite_macosx_aarch64.txt](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/9646011/org.eclipse.jdt.debug.tests.AutomatedSuite_macosx_aarch64.txt)

The stack shows an immense number of waiting TimerTreads, which could be a problem if there are not enough threads to schedule new jobs.

```
java.lang.Exception: ThreadDump for thread "Timer-983"
	at java.base@18.0.1.1/java.lang.Object.wait(Native Method)
	at java.base@18.0.1.1/java.lang.Object.wait(Object.java:338)
	at java.base@18.0.1.1/java.util.TimerThread.mainLoop(Timer.java:537)
	at java.base@18.0.1.1/java.util.TimerThread.run(Timer.java:516)
```

On a quick look, we **might** leak `org.eclipse.debug.internal.ui.viewers.update.EventHandlerModelProxy.fTimer` object by not always disposing `EventHandlerModelProxy` subclass instances, but I haven't verified that.


In both stack traces we see in the final hang dumps:

```
java.lang.Exception: ThreadDump for thread "Worker-8: Debug Event Dispatch"
	at java.base@18.0.1.1/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1051)
	at org.eclipse.debug.internal.ui.viewers.model.TreeModelContentProvider.modelChanged(TreeModelContentProvider.java:523)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy$1.run(AbstractModelProxy.java:92)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy.fireModelChanged(AbstractModelProxy.java:96)
	at org.eclipse.debug.internal.ui.viewers.update.DebugEventHandler.fireDelta(DebugEventHandler.java:169)
	at org.eclipse.debug.internal.ui.viewers.update.DebugTargetEventHandler.fireDelta(DebugTargetEventHandler.java:76)
	at org.eclipse.debug.internal.ui.viewers.update.DebugTargetEventHandler.handleResume(DebugTargetEventHandler.java:59)
	at org.eclipse.debug.internal.ui.viewers.update.EventHandlerModelProxy.dispatchResume(EventHandlerModelProxy.java:222)
	at org.eclipse.debug.internal.ui.viewers.update.EventHandlerModelProxy.handleDebugEvents(EventHandlerModelProxy.java:132)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1226)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1260)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:492)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

and also before we see lot of such log entries:

```
 Some job is still running or waiting to run: 
'Debug Event Dispatch(20)'/org.eclipse.debug.core.DebugPlugin$EventDispatchJob
thread info: "Worker-8: Debug Event Dispatch" prio=5 Id=43 TIMED_WAITING on java.util.Collections$SynchronizedSet@4c3b7811
	at java.base@18.0.1.1/java.lang.Object.wait(Native Method)
	-  waiting on java.util.Collections$SynchronizedSet@4c3b7811
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1051)
	at org.eclipse.debug.internal.ui.viewers.model.TreeModelContentProvider.modelChanged(TreeModelContentProvider.java:523)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy$1.run(AbstractModelProxy.java:92)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy.fireModelChanged(AbstractModelProxy.java:96)
	at org.eclipse.debug.internal.ui.viewers.update.DebugEventHandler.fireDelta(DebugEventHandler.java:169)
	at org.eclipse.debug.internal.ui.viewers.update.DebugTargetEventHandler.fireDelta(DebugTargetEventHandler.java:76)
```

```
Some job is still running or waiting to run: 
'Debug Event Dispatch(20)'/org.eclipse.debug.core.DebugPlugin$EventDispatchJob
thread info: "Worker-0: Debug Event Dispatch" prio=5 Id=33 TIMED_WAITING on java.util.Collections$SynchronizedSet@21969adc
	at java.base@17/java.lang.Object.wait(Native Method)
	-  waiting on java.util.Collections$SynchronizedSet@21969adc
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1051)
	at org.eclipse.debug.internal.ui.viewers.model.TreeModelContentProvider.modelChanged(TreeModelContentProvider.java:523)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy$1.run(AbstractModelProxy.java:92)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy.fireModelChanged(AbstractModelProxy.java:96)
	at org.eclipse.debug.internal.ui.viewers.update.ProcessProxy.fireProcessDelta(ProcessProxy.java:64)
	at org.eclipse.debug.internal.ui.viewers.update.ProcessProxy$1.handleChange(ProcessProxy.java:37)
```


Could be related to [f4d72a08a996c149b0dff89931d9ea85b13134ed](https://github.com/eclipse-platform/eclipse.platform/commit/f4d72a08a996c149b0dff89931d9ea85b13134ed)  (https://github.com/eclipse-platform/eclipse.platform/issues/148).

@jukzi : FYI. This is worrying, if jobs framework has now an issue with `join(family)`

**Comment by iloveeclipse** [comment]
Note, these "DNF" are new in 4.26, so neither EventHandlerModelProxy not TestUtil should be related, as they weren't changed in 4.26.

So we have some bad regression in 4.26.

EventHandlerModelProxy workaround is https://github.com/eclipse-platform/eclipse.platform.debug/pull/83.

**Comment by jukzi** [comment]
I don't see a related stacktace in the logging. Might be the job was not running at the time but only scheduled. there is probably work running in another vm
java.lang.Exception: ThreadDump for thread "Input Stream Monitor for PID 44244 provide-launch-object"
java.lang.Exception: ThreadDump for thread "Process monitor for PID 44244 provide-launch-object"

And with that many threads may have stopped relevant progress.

**Comment by iloveeclipse** [comment]
> Might be the job was not running at the time but only scheduled

```
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1051)
	at org.eclipse.debug.internal.ui.viewers.model.TreeModelContentProvider.modelChanged(TreeModelContentProvider.java:523)
```

this corresponds to `Job.getJobManager().join(ElementContentProvider.class, null);`

The jobs that use this rule are "Debug child count update" and "Debug has children update", but we don't see them reported running in `Some job is still running or waiting to run` outputs (there are many). 
There is only `Debug Event Dispatch` job reported.

> And with that many threads may have stopped relevant progress.

What kind of "relevant progress"?

**Comment by jukzi** [comment]
That test ran slowly - very slow - from  02:02:48.765 04:02:16.086 i.e 2 hours and had steady progress.
Locally the tests finish in ~30min. i don't think there was any kind of deadlock involved but just a damn slow vm.

**Comment by iloveeclipse** [comment]
> That test ran slowly - very slow

Good observation.

I assume they were so slowly because almost every second teardown (via `org.eclipse.jdt.debug.tests.TestUtil.cleanUp(String)`) was affected by hanging "Debug Event Dispatch" that was joining on non existing job family and that join was hanging forever because of changes in https://github.com/eclipse-platform/eclipse.platform/commit/f4d72a08a996c149b0dff89931d9ea85b13134ed.

**Comment by jukzi** [comment]
jdt.debug.tests has DNF for quite some time for example
https://download.eclipse.org/eclipse/downloads/drops4/I20220912-1800/testresults/ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17/org.eclipse.jdt.debug.tests.AutomatedSuite.txt

**Comment by iloveeclipse** [comment]
> jdt.debug.tests has DNF for quite some time for example
> https://download.eclipse.org/eclipse/downloads/drops4/I20220912-1800/

I haven't reported this fail, my bad. I monitor tests every day, so this one must be overlooked by me.

But this build also includes https://github.com/eclipse-platform/eclipse.platform/commit/f4d72a08a996c149b0dff89931d9ea85b13134ed

So still matches my assumption that we have regression in the `JobManager.join()` **or related** code in 4.26.
Such DNF (in `JobManager.join()` called from `TreeModelContentProvider.modelChanged()` ) never happened in 4.25.

Here stack from DNF today where it again hangs on that code **without** related jobs in the thread dump on which this code is supposed to join: https://download.eclipse.org/eclipse/downloads/drops4/I20220926-1800/testresults/ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17/org.eclipse.jdt.debug.tests.AutomatedSuite.txt

This might be connected to https://github.com/eclipse-platform/eclipse.platform.ui/issues/342 

Could it be, the cancelled jobs "done" state may not be "properly" communicated to listeners now, so the jobs are **also** not removed from internal `jobs` list  anymore in https://github.com/eclipse-platform/eclipse.platform/blob/f4d72a08a996c149b0dff89931d9ea85b13134ed/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/JobManager.java#L982

**Comment by iloveeclipse** [comment]
Extracted thread dump from https://download.eclipse.org/eclipse/downloads/drops4/I20220926-1800/testResults.php

[hang_dump_1.txt](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/9653356/hang_dump_1.txt)

There are four thread dumps in the log reported (search for `DumpStackTracesTimer almost reached timeout '7200000'`), but all are **exactly same**.

**Comment by iloveeclipse** [comment]
Looking at the commit in question, I see this comment: "doSchedule will not notify CANCEL_STATUS" in https://github.com/eclipse-platform/eclipse.platform/blob/f4d72a08a996c149b0dff89931d9ea85b13134ed/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/JobManager.java#L722

I'm not sure what that mean because I haven't debugged this code, but this sounds exact like like the problem we observe now.

I suspect if the changes in `JobManager.endJob()` affect listener in `JobManager.join()` in a way the internal `jobs` is not properly updated now.

**Comment by jukzi** [comment]
That comment was just to remember, that scheduleInternal will not send any notification while holing the lock. Any notification is send in :733 via scheduleNotify outside the lock.
Let's try to create a junit for the cancel case that reproduces the problem(s).

**Comment by jukzi** [comment]
Wait, tonight's hung was a join on ElementContentProvider i.e. ElementContentProviderJob which is never canceled. Why do you think it has something todo with cancel?

```
java.lang.Exception: ThreadDump for thread "Test Runner"
	at java.base@17/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1051)
	at org.eclipse.debug.internal.ui.viewers.model.TreeModelContentProvider.modelChanged(TreeModelContentProvider.java:523)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy$1.run(AbstractModelProxy.java:92)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.ui.viewers.provisional.AbstractModelProxy.fireModelChanged(AbstractModelProxy.java:96)
	at org.eclipse.debug.internal.ui.viewers.update.LaunchProxy.fireDelta(LaunchProxy.java:167)
	at org.eclipse.debug.internal.ui.viewers.update.LaunchProxy.launchesChanged(LaunchProxy.java:104)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.run(LaunchManager.java:302)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.notify(LaunchManager.java:262)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1057)
	at org.eclipse.debug.core.Launch.fireChanged(Launch.java:466)
	at org.eclipse.debug.core.Launch.addProcess(Launch.java:419)
	at org.eclipse.debug.core.model.RuntimeProcess.<init>(RuntimeProcess.java:157)
	at org.eclipse.debug.core.DebugPlugin.newProcess(DebugPlugin.java:830)
	at org.eclipse.jdt.launching.AbstractVMRunner.newProcess(AbstractVMRunner.java:169)
	at org.eclipse.jdt.internal.launching.StandardVMDebugger.run(StandardVMDebugger.java:348)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:176)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1180)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1164)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1397)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1379)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1366)
	at org.eclipse.jdt.debug.tests.breakpoints.MethodBreakpointTests.testDisabledEntryAndExitBreakpoints(MethodBreakpointTests.java:130)
	at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2678)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
	at java.base@17/java.lang.Thread.run(Thread.java:833)
```

**Comment by iloveeclipse** [comment]
> Why do you think it has something todo with cancel?

Because of the similar UI issue with cancelled jobs are not removed from Progress view anymore.

The common pattern is: we have job listeners and in the case of join() on a family we will loop forever if the terminated jobs aren't removed from the list. The must not be necessarily cancelled, but all the entries I saw in the Progress were shown as "cancelled".

So I draw a conclusion: 
1) I never saw "hanging cancelled" jobs in Progress view before 4.26
2) I never saw debug test hanging on `JobManager.join()` before 4.26
3) This would be a very strange coincidence if that would be not related to the recent changes on job scheduling.

**Comment by iloveeclipse** [comment]
Fixed by one of platform job framework patches.
