### ISSUE TITLE
JDI low level tracing is not thread safe & breaks debugger

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#160]
We experience issues with JVM's started under debugger & to analyze them, I've looked into (ancient not documented) low level JDI debugging in Eclipse.

Good news: if one knows how to enable it, it seem to work.
Bad news: it is hardly usable in general and breaks debugger if application uses multiple threads.

Issues I saw so far:

1) Enabling low level JDI debug is not documented at all
2) The way it is enabled is unusual and doesn't use "tracing" Eclipse capabilities
3) Once enabled, it spams log even if application is idling
4) If application uses multiple threads, breakpoints handling (and probably other JDI related actions) causes debugger to fail with error dialogs, unresponsible debuggee process and other various issues.

**Points 1 and 2 - unusual way to enable tracing**
The way how JDI debugging is activated see https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/0c8c6d9fa30cda3c83741613f6ea4c541c037973/org.eclipse.jdt.debug/jdi/org/eclipse/jdi/internal/VirtualMachineManagerImpl.java#L113 is to search **org.eclipse.jdt.debug bundle** classpath for a `jdi.ini` file, where following properties are expected:
```
User.verbose=true
# Default is system.out
Verbose.out=/tmp/jdi_dump.txt
```
I don't understand why that was done in such way, tracing `.options` file was submitted in **same** commit 3c7939022de48bfa72324a4d2451d33cfb56a6d0

For developers today it means, one has to provide a **fragment** to org.eclipse.jdt.debug that includes the preferences file in the source root. That is of course neither selective for a specific test nor can be disabled after the test. Example fragment I've used to play with: 
[jdi_fragment_to_enable_tracing.zip](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/10154293/jdi_fragment_to_enable_tracing.zip)

Anyway, number 1 & 2 could be fixed by using default tracing functionality.

**Point 3 - log spamming**
This is coming from the fact that idling debugger still pings JVM every second in https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/0c8c6d9fa30cda3c83741613f6ea4c541c037973/org.eclipse.jdt.debug/model/org/eclipse/jdt/internal/debug/core/EventDispatcher.java#L298 and gets timeout exception if nothing is there:
```
org.eclipse.jdi.TimeoutException
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getCommand(PacketReceiveManager.java:145)
	at org.eclipse.jdi.internal.MirrorImpl.getCommandVM(MirrorImpl.java:334)
	at org.eclipse.jdi.internal.event.EventQueueImpl.remove(EventQueueImpl.java:71)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher.run(EventDispatcher.java:298)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Can be fixed by not tracing TimeoutException.

**Point 4 - debugger errors on MT code**

This is most interesting one. 

Consider this test case:
```
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class TestJdiLogging {
	private static ExecutorService pool;

	public static void main(String[] args) throws Exception {
		pool = Executors.newFixedThreadPool(2);
		pool.submit(() -> method());
		pool.submit(() -> method());
		pool.submit(() -> method());
		pool.submit(() -> method());
		pool.submit(() -> method());
		pool.submit(() -> method());
		while(true) {
			Thread.sleep(100);
		}
	}

	private static void method() {
		pool.submit(() -> method()); // Conditional breakpoint "return false"
	}
}
```
The code simply calls same method from different threads. The method has a (conditional for demonstration) breakpoint that does "nothing". I see debugger errors immediately after start if I enable JDI tracing.

The code in https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/0c8c6d9fa30cda3c83741613f6ea4c541c037973/org.eclipse.jdt.debug/jdi/org/eclipse/jdi/internal/VerboseWriter.java#L38 is simply not thread safe. Probably that wasn't an issue at time of Eclipse 3.1, or the code wasn't ever tested, I don't know. But debugging any MT code leads sooner or later to such exceptions that break debugger in many places:
```
!ENTRY org.eclipse.core.jobs 4 2 2022-12-05 13:46:53.194
!MESSAGE An internal error occurred during: "JDI Expression Evaluation Event Dispatch".
!STACK 0
java.lang.IndexOutOfBoundsException: Index 248 out of bounds for length 248
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.eclipse.jdi.internal.VerboseWriter.print(VerboseWriter.java:504)
	at org.eclipse.jdi.internal.VerboseWriter.printWidth(VerboseWriter.java:232)
	at org.eclipse.jdi.internal.VerboseWriter.printHexSubstitution(VerboseWriter.java:250)
	at org.eclipse.jdi.internal.VerboseWriter.printHex(VerboseWriter.java:368)
	at org.eclipse.jdi.internal.VerboseWriter.println(VerboseWriter.java:170)
	at org.eclipse.jdi.internal.MirrorImpl.readString(MirrorImpl.java:457)
	at org.eclipse.jdi.internal.MethodImpl.readWithNameSignatureModifiers(MethodImpl.java:744)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.methods(ReferenceTypeImpl.java:1149)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.findMethod(ReferenceTypeImpl.java:987)
	at org.eclipse.jdi.internal.MethodImpl.readWithReferenceTypeWithTag(MethodImpl.java:719)
	at org.eclipse.jdi.internal.LocationImpl.read(LocationImpl.java:181)
	at org.eclipse.jdi.internal.StackFrameImpl.readWithLocation(StackFrameImpl.java:366)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:292)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:256)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.getUnderlyingFrames(JDIThread.java:727)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.computeStackFrames(JDIThread.java:621)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.computeStackFrames(JDIThread.java:698)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.getTopStackFrame(JDIThread.java:1343)
	at org.eclipse.jdt.internal.debug.core.breakpoints.ConditionalBreakpointHandler.breakpointHit(ConditionalBreakpointHandler.java:217)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpointInternal(JDIThread.java:1428)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpoint(JDIThread.java:1368)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.suspend(JavaBreakpoint.java:410)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleBreakpointEvent(JavaBreakpoint.java:399)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleEvent(JavaBreakpoint.java:315)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher.dispatch(EventDispatcher.java:190)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher$1.run(EventDispatcher.java:311)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2022-12-05 13:46:53.194
!MESSAGE An internal error occurred during: "JDI Expression Evaluation Event Dispatch".
!STACK 0
java.lang.IndexOutOfBoundsException: Index 210 out of bounds for length 210
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.eclipse.jdi.internal.VerboseWriter.print(VerboseWriter.java:504)
	at org.eclipse.jdi.internal.VerboseWriter.printHexSubstitution(VerboseWriter.java:249)
	at org.eclipse.jdi.internal.VerboseWriter.printHex(VerboseWriter.java:368)
	at org.eclipse.jdi.internal.VerboseWriter.println(VerboseWriter.java:170)
	at org.eclipse.jdi.internal.MirrorImpl.readString(MirrorImpl.java:457)
	at org.eclipse.jdi.internal.MethodImpl.readWithNameSignatureModifiers(MethodImpl.java:748)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.methods(ReferenceTypeImpl.java:1149)
	at org.eclipse.jdi.internal.ReferenceTypeImpl.findMethod(ReferenceTypeImpl.java:987)
	at org.eclipse.jdi.internal.MethodImpl.readWithReferenceTypeWithTag(MethodImpl.java:719)
	at org.eclipse.jdi.internal.LocationImpl.read(LocationImpl.java:181)
	at org.eclipse.jdi.internal.StackFrameImpl.readWithLocation(StackFrameImpl.java:366)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:292)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:256)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.getUnderlyingFrames(JDIThread.java:727)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.computeStackFrames(JDIThread.java:621)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.computeStackFrames(JDIThread.java:698)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.getTopStackFrame(JDIThread.java:1343)
	at org.eclipse.jdt.internal.debug.core.breakpoints.ConditionalBreakpointHandler.breakpointHit(ConditionalBreakpointHandler.java:217)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpointInternal(JDIThread.java:1428)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpoint(JDIThread.java:1368)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.suspend(JavaBreakpoint.java:410)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleBreakpointEvent(JavaBreakpoint.java:399)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleEvent(JavaBreakpoint.java:315)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher.dispatch(EventDispatcher.java:190)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher$1.run(EventDispatcher.java:311)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

![image](https://user-images.githubusercontent.com/964108/205641226-f35e0e12-48c4-4946-a5fd-5ac65786d6ee.png)

I plan to provide some fixes to make low level JDI tracing working again.

**Comment by SarikaSinha** [comment]
Overall the changes looks good, have 2 concerns 
1. Looking at https://www.eclipse.org/lists/jdt-dev/msg01085.html I was wondering can we just add the tracing but not remove the old way as we don't know who all knows and uses it in which form
2. I believe it should be safe to remove org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()?

**Comment by iloveeclipse** [comment]
Before removing jdi.ini I've googled for this file and found exact one link in the forum you're mentioning and another one unanswered question about its use.
I can't imagine this is widely used, useful or was ever published as an official way to trace JDI in Eclipse.

I think it is simply not worth to keep old undocumented and hackish approach given the new one does same in a way **everyone else** does it in Eclipse, and doesn't require any magic or bundle manipulation etc.

I will check org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()

**Comment by iloveeclipse** [comment]
> 2\. I believe it should be safe to remove org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()?

Sorry, I don't see `org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()` - did you mean something else?

**Comment by SarikaSinha** [comment]
> > 2. I believe it should be safe to remove org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()?
> 
> Sorry, I don't see `org.eclipse.jdi.internal.MirrorImpl.handledJdwpEventSet()` - did you mean something else?
<img width="901" alt="image" src="https://user-images.githubusercontent.com/14090181/206460842-abb6ca4c-76be-4333-b9af-21e6bf1d9c50.png">

**Comment by iloveeclipse** [comment]
OK, this is just `handledJdwpEventSet() -> handledJdwpEventSet(Throwable)` signature change, the old method has now one parameter.
