### ISSUE TITLE
"Source not found" in debugger because of NPE in MavenSourceContainerResolver

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.debug#171]
I executed my program (with the Tomcat server) and when a debug breakpoint hit then the debugger showed me "Source not found." Restarting the debugging session did not help. Restarting Eclipse also didn't help.

I solved the problem by creating a new Tomcat Server (cleaning the existing server did not help).

The error log says:
```
java.lang.NullPointerException: Cannot invoke "java.util.Collection.isEmpty()" because "classesArtifacts" is null
	at org.eclipse.m2e.sourcelookup.internal.launch.MavenSourceContainerResolver.resolveSourceContainers(MavenSourceContainerResolver.java:40)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.getSourceContainer(AdvancedSourceLookupParticipant.java:144)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.findSourceElements(AdvancedSourceLookupParticipant.java:72)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:138)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:473)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:714)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:303)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupTask.run(SourceLookupFacility.java:752)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:690)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The corresponding session data:
```
eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/xxx/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/xxx/dev/workspaces/master/ -product org.eclipse.epp.package.jee.product -keyring /Users/xxx/.eclipse_keyring
```

**Comment by iloveeclipse** [comment]
Please report this to m2e.

**Comment by jubax** [comment]
Reported to https://github.com/eclipse-m2e/m2e-core/issues/1170

Thanks

**Comment by laeubi** [comment]
> Please report this to m2e.

I think this is still a bug in JDT... whatever happens here 

-  Restarting the debugging session did not help.
-  Restarting Eclipse also didn't help.

is not really acceptable, and `org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant` should catch runtime exceptions and probably show a more focused error message.

**Comment by iloveeclipse** [comment]
> is not really acceptable, and `org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant` should catch runtime exceptions and probably show a more focused error message.

Well, it is conform to the API contract of `org.eclipse.jdt.launching.sourcelookup.advanced.ISourceContainerResolver.resolveSourceContainers(File, IProgressMonitor) throws CoreException` that says as of today:

`Creates and returns a collection of source containers that correspond to the given filesystem classes location. Returns null or an empty collection if requested sources cannot be located.`

The clients that are contributing to the extension point aren't supposed to throw anything **except** `CoreException`.
So it's up to m2e code to try/catch NPE's and provide more specific handling of that NPE or re-throw as  `CoreException`.

**Comment by laeubi** [comment]
A runtime exception is for sure not expected, but whenever working with extension code it is always good to expect the unexpected :-)

i won't expect it to handle it in any usefull maner other than e.g. writing it to the error log something like:

The source provider `MavenSourceContainerResolver` has thrown an internal error and is ignore, please blame them for the issue so it gets fixed

**Comment by iloveeclipse** [comment]
> whenever working with extension code it is always good to expect the unexpected

You knkw, that all of Eclipse is based on extensions. Putting every call to extensions code into try/catch Throwable is not really a solution.

> i won't expect it to handle it in any usefull maner

So if you have no idea, wrap to CoreException and let the platform do whatever it was supposed to do on exception.
