### ISSUE TITLE
NPE if JavaDebugOptionsManager.AskRecurrenceDialog is closed

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#176]
NPE happens if the dialog below is closed by clicking on "x" in upper right corner (not with "Skip" or "Repeat"):
![image](https://user-images.githubusercontent.com/964108/213702113-ecfba801-f0ee-4140-b7c8-44d7a1cef073.png)

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.debug.core.IJavaExceptionBreakpoint$SuspendOnRecurrenceStrategy.ordinal()" because "skip" is null
    at org.eclipse.jdt.internal.debug.ui.JavaDebugOptionsManager.shouldSkipSubsequentOccurrence(JavaDebugOptionsManager.java:621)
    at org.eclipse.jdt.internal.debug.ui.JavaDebugOptionsManager.breakpointHit(JavaDebugOptionsManager.java:588)
    at org.eclipse.jdt.internal.debug.core.JDIDebugPlugin$HitNotifier.run(JDIDebugPlugin.java:765)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.jdt.internal.debug.core.JDIDebugPlugin$AbstractNotifier.notifyListeners(JDIDebugPlugin.java:581)
    at org.eclipse.jdt.internal.debug.core.JDIDebugPlugin$HitNotifier.notifyHit(JDIDebugPlugin.java:781)
    at org.eclipse.jdt.internal.debug.core.JDIDebugPlugin.fireBreakpointHit(JDIDebugPlugin.java:517)
    at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpointInternal(JDIThread.java:1454)
    at org.eclipse.jdt.internal.debug.core.model.JDIThread.handleSuspendForBreakpoint(JDIThread.java:1368)
    at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.suspend(JavaBreakpoint.java:410)
    at org.eclipse.jdt.internal.debug.core.breakpoints.JavaExceptionBreakpoint.handleBreakpointEventInternal(JavaExceptionBreakpoint.java:446)
    at org.eclipse.jdt.internal.debug.core.breakpoints.JavaExceptionBreakpoint.handleBreakpointEvent(JavaExceptionBreakpoint.java:369)
```

NPE is coming from 868164ebfbf1b371470f438022eef52b50481496 / https://bugs.eclipse.org/bugs/show_bug.cgi?id=284158.

I plan to push a patch.

**Comment by iloveeclipse** [comment]
```
Set a breakpoint on NullPointerException and debug this program:

//--
package dbg;

public class Main {
	public static void main(String[] args) {
		new Main().m1();
	}

	private void m1() {
		try {
			m2();
		} finally {
			System.err.println("cleanup in m1()");
		}
	}

	private void m2() {
		try {
			m3(null);
		} catch (NullPointerException e) {
			e.printStackTrace();
			throw e;
		}
	}

	private void m3(String s) {
		System.out.println(s.toLowerCase());
	}
}
```
