### ISSUE TITLE
The source code of some javaFx classes is no longer accessible at debugging in Eclipse

### ISSUE THREAD

**Issue by Graou74** [eclipse-jdt/eclipse.jdt.debug#188]
Repeat here of the problem described at: https://github.com/eclipse-platform/eclipse.platform.debug/issues/117

It looks like it would be the 'Preference/Java/Debug/Use advanced source loockup' option that is causing source detection to fail with the source attachment.

Here is the log file retrieved when running in debug:
[ .log](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/10864119/default.log)

**Comment by SarikaSinha** [comment]
@mickaelistria 
From the log it looks like the issue needs to handled in m2e. Can we create an issue there?
java.lang.NullPointerException: Cannot invoke "java.util.Collection.isEmpty()" because "classesArtifacts" is null
	at org.eclipse.m2e.sourcelookup.internal.launch.MavenSourceContainerResolver.resolveSourceContainers(MavenSourceContainerResolver.java:40)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.getSourceContainer(AdvancedSourceLookupParticipant.java:144)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.findSourceElements(AdvancedSourceLookupParticipant.java:72)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:138)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:473)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:714)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:303)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupTask.run(SourceLookupFacility.java:752)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:690)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by iloveeclipse** [comment]
Yes, same as https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/171

**Comment by mickaelistria** [comment]
Thanks all for the input allowing to identify it's https://github.com/eclipse-m2e/m2e-core/issues/1170 .
@Graou74 you can install m2e snapshots ( https://github.com/eclipse-m2e/m2e-core/blob/master/README.md#-installation ) to get the fix; this should be part of upcoming release in a couple of weeks.

**Comment by Graou74** [comment]
What amazing responsiveness. Thanks for your help.

**Comment by Graou74** [comment]
The fix is installed and working 👍
