### ISSUE TITLE
SourceLocationTests fail since BETA_JAVA20 merge

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#212]
See https://download.eclipse.org/eclipse/downloads/drops4/I20230323-1800/testresults/html/org.eclipse.jdt.debug.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

- testNegativeSystemLibrarySourceLocation
- testPositiveSystemLibrarySourceLocation

fail with similar stack traces:

```
Could not find JRE_CONTAINER entry

junit.framework.AssertionFailedError: Could not find JRE_CONTAINER entry
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNotNull(Assert.java:256)
at junit.framework.TestCase.assertNotNull(TestCase.java:399)
at org.eclipse.jdt.debug.tests.sourcelookup.SourceLocationTests.testNegativeSystemLibrarySourceLocation(SourceLocationTests.java:215)
```

**Comment by iloveeclipse** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/213, probably related?

**Comment by iloveeclipse** [comment]
> See also #213, probably related?

Nope, this must be a regression from ab8481645dc85775232f1c8cff7dce34e104204f, the fix is trivial, I will push it in a moment.
