### ISSUE TITLE
org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests is failing in macosx.cocoa.x86_64 

### ISSUE THREAD

**Issue by Shee43** [eclipse-jdt/eclipse.jdt.debug#225]
This Unit Test was failing in [I20230326-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230326-1800/) Integration Build  but was not reproducible locally.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/122248524/228442607-c5b6463e-9b1f-465e-91b9-e7abf660d426.png">

**Comment by iloveeclipse** [comment]
@Shee43 : just a hint: better is to copy/paste **text** with the stack trace that can be pasted into SDK console.
```
Evaluation of 'predicate' should not have exception : null

junit.framework.AssertionFailedError: Evaluation of 'predicate' should not have exception : null
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNull(Assert.java:277)
at junit.framework.TestCase.assertNull(TestCase.java:418)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.doEval(AbstractDebugTest.java:2793)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.doEval(AbstractDebugTest.java:2756)
at org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests.testEvaluateMethodParameter_DeepInTwoNestedClasses(SyntheticVariableTests.java:90)
```

Note: this test is OK on recent builds, means it is an unstable test.
