### ISSUE TITLE
No links in process console / Java stack trace console for stack traces with module names

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#23]
Start jvm with argument `-Dfile.encoding=` (no charset defined by mistake).
No links in process console / Java stack trace console for stack traces with module names
```
Error occurred during initialization of VM
java.nio.charset.IllegalCharsetNameException: 
	at java.nio.charset.Charset.checkName(java.base/Charset.java:296)
	at java.nio.charset.Charset.lookup2(java.base/Charset.java:482)
	at java.nio.charset.Charset.lookup(java.base/Charset.java:462)
	at java.nio.charset.Charset.defaultCharset(java.base/Charset.java:608)
	at java.io.OutputStreamWriter.<init>(java.base/OutputStreamWriter.java:110)
	at java.io.PrintStream.<init>(java.base/PrintStream.java:110)
	at java.io.PrintStream.<init>(java.base/PrintStream.java:148)
	at java.lang.System.newPrintStream(java.base/System.java:1898)
	at java.lang.System.initPhase1(java.base/System.java:1974)
```

**Comment by SarikaSinha** [comment]
What is the expectation here?

**Comment by iloveeclipse** [comment]
All the classes formatted like `java.base/Charset.java:296` should be underlined. Right now they aren't

**Comment by iloveeclipse** [comment]
@trancexpress , @jukzi : I wonder if you can look on your recent changes and improve the regex used? Would be faster as if I would do that.

**Comment by trancexpress** [comment]
> @trancexpress , @jukzi : I wonder if you can look on your recent changes and improve the regex used? Would be faster as if I would do that.

I don't think this relates to the changes for parsing Debug view stack traces? The format above is from Java. I can look into that too, sure.

**Comment by trancexpress** [comment]
The pattern seems to not be provided in the ```plugin.xml``` file, instead its constructed here:

```
"main" #1 prio=6 os_prio=0 cpu=8460.31ms elapsed=132.91s tid=0x00007ffff0018000 nid=0xe39e runnable  [0x00007ffff7fc8000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.debug.ui.console.JavaLikeExtensionsResolver.resolveValue(JavaLikeExtensionsResolver.java:33)
        at org.eclipse.core.internal.variables.DynamicVariable.getValue(DynamicVariable.java:56)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.resolve(StringSubstitutionEngine.java:271)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.substitute(StringSubstitutionEngine.java:195)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.performStringSubstitution(StringSubstitutionEngine.java:91)
        at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:547)
        at org.eclipse.ui.internal.console.PatternMatchListenerExtension.getPattern(PatternMatchListenerExtension.java:109)
        at org.eclipse.ui.internal.console.PatternMatchListener.getPattern(PatternMatchListener.java:34)
        at org.eclipse.ui.internal.console.ConsolePatternMatcher.addPatternMatchListener(ConsolePatternMatcher.java:220)
        - locked <0x000000014acc0738> (a java.util.ArrayList)
        at org.eclipse.ui.console.TextConsole.addPatternMatchListener(TextConsole.java:454)
        at org.eclipse.ui.internal.console.ConsoleManager.createPatternMatchListeners(ConsoleManager.java:408)
        at org.eclipse.ui.internal.console.ConsoleManager.addConsoles(ConsoleManager.java:209)
        - locked <0x00000001506ea2c0> (a java.util.ArrayList)
        at org.eclipse.jdt.debug.ui.console.JavaStackTraceConsoleFactory.openConsole(JavaStackTraceConsoleFactory.java:76)
        at org.eclipse.jdt.debug.ui.console.JavaStackTraceConsoleFactory.openConsole(JavaStackTraceConsoleFactory.java:58)
        at org.eclipse.jdt.debug.tests.console.AbstractJavaStackTraceConsoleTest.initConsole(AbstractJavaStackTraceConsoleTest.java:91)
        at org.eclipse.jdt.debug.tests.console.AbstractJavaStackTraceConsoleTest.lambda$0(AbstractJavaStackTraceConsoleTest.java:74)
        at org.eclipse.jdt.debug.tests.console.AbstractJavaStackTraceConsoleTest$$Lambda$768/0x00000008409bc440.run(Unknown Source)
        at org.eclipse.jdt.debug.tests.ui.AbstractDebugUiTests.lambda$5(AbstractDebugUiTests.java:203)
        at org.eclipse.jdt.debug.tests.ui.AbstractDebugUiTests$$Lambda$769/0x00000008409f7840.run(Unknown Source)
        at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
        at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
        at org.eclipse.swt.widgets.Display.syncExec(Display.java:5912)
        at org.eclipse.jdt.debug.tests.ui.AbstractDebugUiTests.sync(AbstractDebugUiTests.java:201)
        at org.eclipse.jdt.debug.tests.console.AbstractJavaStackTraceConsoleTest.setUp(AbstractJavaStackTraceConsoleTest.java:74)
        at junit.framework.TestCase.runBare(TestCase.java:140)
        at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2671)
```

**Comment by trancexpress** [comment]
No idea how to correctly link my PR to this issue, how to formulate the commit message. @iloveeclipse ?

https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/46

**Comment by iloveeclipse** [comment]
> No idea how to correctly link my PR to this issue and how to formulate the commit message. ?

I personally use git history A LOT and I appreciate if the full link to the issue would be added to the commit message, so one can open the github ticket directly from Eclipse without extra steps.

In general, we have a guideline to put the issue number to the commit message like:
```
No links in process console / Java stack trace console for stack traces with module names (Fixes #23)

This commit does some very clever things like ....
- bla
- blup
- etc

See https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/23
```

**Comment by jukzi** [comment]
its not only the issue number, but also a magic word thats needs to be added to get the link:
see
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
"fixes" is one of them

**Comment by iloveeclipse** [comment]
Verified with I20220515-1800. Thanks Simeon.
