### ISSUE TITLE
OpenFromClipboardTests still randomly fail

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#28]
I assume something like running other jobs (charset delta, autobuild) etc might confuse Java search.
Let disable autobuild, wait for charset delta job that might be running & see if that helps.

https://download.eclipse.org/eclipse/downloads/drops4/I20220419-1800/testresults/html/org.eclipse.jdt.debug.tests_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html
```
junit.framework.AssertionFailedError: expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.Assert.assertEquals(Assert.java:241)
at junit.framework.TestCase.assertEquals(TestCase.java:384)
at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testStackElement_2(OpenFromClipboardTests.java:587)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20220419-1800/testresults/html/org.eclipse.jdt.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
```
junit.framework.AssertionFailedError: expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.Assert.assertEquals(Assert.java:241)
at junit.framework.TestCase.assertEquals(TestCase.java:384)
at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMember_1(OpenFromClipboardTests.java:462)
```

**Comment by iloveeclipse** [comment]
Failed again:
```
expected:<1> but was:<0>

junit.framework.AssertionFailedError: expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.Assert.assertEquals(Assert.java:241)
at junit.framework.TestCase.assertEquals(TestCase.java:384)
at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMember_3(OpenFromClipboardTests.java:491)
```

```
junit.framework.AssertionFailedError: expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.Assert.assertEquals(Assert.java:241)
at junit.framework.TestCase.assertEquals(TestCase.java:384)
at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMethod_6(OpenFromClipboardTests.java:390)
```

**Comment by SarikaSinha** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800/testresults/html/org.eclipse.jdt.debug.tests_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by subyssurendran666** [comment]
Failed again 
[https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.jdt.debug.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.jdt.debug.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html)

**Comment by Shee43** [comment]
Failed again 
https://download.eclipse.org/eclipse/downloads/drops4/I20230601-1220/testresults/html/org.eclipse.jdt.debug.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by Shee43** [comment]
Failed again
https://download.eclipse.org/eclipse/downloads/drops4/I20230703-0600/testresults/html/org.eclipse.jdt.debug.tests_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html

**Comment by fedejeanne** [comment]
`org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMethod_6` failed again in [this check](https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/277/checks?check_run_id=14828844308) of #277

**Comment by fedejeanne** [comment]
I created a PR to help identify the underlying cause of the failures --> #279 .

I do have a question though, perhaps someone has a hint. Does anyone know why the call to `fAccessor.invoke("getJavaElementMatches", ... )` in the private method `OpenFromClipboardTests::getJavaElementMatches(String)` needs to run through the `Display` class? I mean why call:
```
Display.getDefault().syncExec(new Runnable() {
			@Override
			public void run() {
				fAccessor.invoke("getJavaElementMatches", new Class[] { String.class, List.class }, new Object[] { textData, matches });
			}
		});
```
... when I can simply call:
```
fAccessor.invoke("getJavaElementMatches", new Class[] { String.class, List.class }, new Object[] { textData, matches });
```

?

Is it just to make sure that all other UI-blocking tasks like indexing and encoding are done before calling the `Runnable`? If yes, hasn't that already been achieved by calling `OpenFromClipboardTests::waitForEncodingRelatedJobs()` ?
