### ISSUE TITLE
OutOfMemory in Java Indexing thread when JVM detection is enabled.

### ISSUE THREAD

**Issue by rgrunber** [eclipse-jdt/eclipse.jdt.debug#283]
First noticed in the quarkus-ls maven builds at https://github.com/redhat-developer/quarkus-ls/actions/runs/5477437137

```
Error: Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
	at jdk.internal.jimage.BasicImageReader.getBufferBytes(BasicImageReader.java:356)
	at jdk.internal.jimage.BasicImageReader.getResource(BasicImageReader.java:412)
	at jdk.internal.jimage.ImageReader$SharedImageReader.getResource(ImageReader.java:569)
	at jdk.internal.jimage.ImageReader.getResource(ImageReader.java:109)
	at jdk.internal.jrtfs.SystemImage$1.getResource(SystemImage.java:69)
	at jdk.internal.jrtfs.JrtFileSystem.getFileContent(JrtFileSystem.java:250)
	at jdk.internal.jrtfs.JrtFileSystem.newByteChannel(JrtFileSystem.java:343)
	at jdk.internal.jrtfs.JrtPath.newByteChannel(JrtPath.java:702)
	at jdk.internal.jrtfs.JrtFileSystemProvider.newByteChannel(JrtFileSystemProvider.java:305)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.safeReadBytes(JRTUtil.java:323)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.lambda$1(JRTUtil.java:669)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$$Lambda$333/0x0000000801494460.apply(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.getFileBytes(JRTUtil.java:667)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.getClassfileContent(JRTUtil.java:648)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getClassfileContent(JRTUtil.java:268)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtIndexer.visitFile(AddJrtToIndex.java:140)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtTraverser.visitFile(AddJrtToIndex.java:1)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:781)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(JRTUtil.java:750)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:244)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex.execute(AddJrtToIndex.java:267)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:514)
	at org.eclipse.jdt.internal.core.search.processing.JobManager$$Lambda$159/0x000000080126a240.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It's reproducible locally, though in my case I needed to have `java-11-openjdk-headless-11.0.19.0.7-1.fc37.x86_64` package installed. My guess is certain JVMs are not being nicely handled by the JVM detection feature.

```
$ git clone https://github.com/redhat-developer/quarkus-ls.git && cd quarkus-ls && git checkout 3400541
$ cd quarkus.jdt.ext
$ ./mvnw clean verify
```
You can even monitor quarkus.jdt.ext/target/surefire-reports for java.lang.OutOfMemory in the report files.

You'll see various `java.lang.OutOfMemory: Java heap space` exceptions. I tried reproducing this in Eclipse itself but haven't been able to yet. I did notice the behaviour through other clients (ie. vscode-java -> JDT-LS) :

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/1417342/12d43c34-0c4b-4c03-a655-1f0ab91a4b86)

Known workarounds :
- `-DDetectVMInstallationsJob.disabled=true`
- Any build/commit prior to the JVM detection feature (eg. https://download.eclipse.org/eclipse/downloads/drops4/I20230612-1800/ )

CC @mickaelistria

**Comment by iloveeclipse** [comment]
How many VM's were found and how big is the heap?

**Comment by iloveeclipse** [comment]
Can you create memory dump or just simple memory histogram via jcmd tool?

**Comment by iloveeclipse** [comment]
> I could make the issue disappear completely by just removing java-11-openjdk.

Any chance to get this installation as zip or rpm(s) attached? I assume something (broken/cyclic links etc) could lead to adding too much data to index.

Also you could try to start Eclipse and manually add this installation to list of JRE's - would it explode too?

**Comment by iloveeclipse** [comment]
Looking on the histogram I wonder if what we see is not related to SDK code but to the VS specific wrapper around JDT.

Looking on instance numners I can imagine there could be maps managed by maven/aether filled with lot of byte and character arrays.

10:         39152        1879296  java.util.HashMap (java.base@17.0.7) 
11:         57528        1840896  org.apache.maven.model.InputLocation
12:         18660        1791360  org.apache.maven.model.Dependency

18:         31279        1000928  jdk.internal.jimage.ImageReader$Resource
19:         24801         992040  org.eclipse.aether.artifact.DefaultArtifact
20:         30752         984064  jdk.internal.jrtfs.JrtPath

**Comment by rgrunber** [comment]
https://kojipkgs.fedoraproject.org//packages/java-11-openjdk/11.0.19.0.7/1.fc37/x86_64/java-11-openjdk-headless-11.0.19.0.7-1.fc37.x86_64.rpm . I'll try to see if I can reproduce in an Eclipse I-build (likely with m2e). I noticed that the OOM occurred on project import of some Maven project. The only way I've been able to reproduce consistently is by running the quarkus-ls tests.

**Comment by mickaelistria** [comment]
OK, so I think the issue is not in JVM detection itself. The JVM detection does it job and detects the JVM.
However, it detect 1 particular JVM that cause issue. Looking at the code sending the exception, it's an array instantiation so it adds credit to what VisualVM says: there is no excessive memory consumption... until that exact line. The most probable is the the size of the array is clearly too big for the JVM to instantiate it and the instantiation fails before even trying to assign memory. It seems like `JrtFileSystem.getFileBytes` tries to read some *huge* file from this JVM. Can you please check whether there could be a huge file in this JVM installation, or a fishy one that would lead to an error in reading its size?

**Comment by jukzi** [comment]
why is this issue in DEBUG? move to CORE?

**Comment by jukzi** [comment]
Is this still an issue? Please either provide information which detected jdk file causes the error or close.
