### ISSUE TITLE
An internal error occurred during: "Look up for installed JVMs".

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-jdt/eclipse.jdt.debug#289]
Starting up eclipse-SDK-I20230802-1800-macosx-cocoa-aarch64 causes this:

<img width="1027" alt="Screenshot 2023-08-03 at 11 53 56" src="https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/28338612/a0c6642b-77b3-4931-b0c3-84d26065c509">

The error log shows this:
java.lang.UnsupportedOperationException: remove
	at java.base/java.util.Iterator.remove(Iterator.java:102)
	at java.base/java.util.Collection.removeIf(Collection.java:577)
	at org.eclipse.jdt.internal.launching.DetectVMInstallationsJob.run(DetectVMInstallationsJob.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Seems to be related to #265 and #231

**Comment by SarikaSinha** [comment]
@jjohnstn 
Can you look into this?

**Comment by jjohnstn** [comment]
@SarikaSinha Will do.
