### ISSUE TITLE
[Tests] testMapLogicalStructure tests failing on gtk3

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#301]
https://download.eclipse.org/eclipse/downloads/drops4/I20230830-2200/testresults/html/org.eclipse.jdt.debug.tests_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html
com.sun.jdi.ObjectCollectedException occurred retrieving type

org.eclipse.debug.core.DebugException: com.sun.jdi.ObjectCollectedException occurred retrieving type
at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.throwDebugException(JDIDebugElement.java:263)
at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.requestFailed(JDIDebugElement.java:202)
at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.targetRequestFailed(JDIDebugElement.java:182)
at org.eclipse.jdt.internal.debug.core.model.JDIValue.getUnderlyingType(JDIValue.java:459)
at org.eclipse.jdt.internal.debug.core.model.JDIValue.getJavaType(JDIValue.java:441)
at org.eclipse.jdt.debug.tests.variables.TestLogicalStructures.testMapLogicalStructure(TestLogicalStructures.java:109)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2678)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: com.sun.jdi.ObjectCollectedException
at org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(MirrorImpl.java:295)
at org.eclipse.jdi.internal.ObjectReferenceImpl.referenceType(ObjectReferenceImpl.java:531)
at org.eclipse.jdi.internal.ObjectReferenceImpl.type(ObjectReferenceImpl.java:548)
at org.eclipse.jdt.internal.debug.core.model.JDIValue.getUnderlyingType(JDIValue.java:457)

**Comment by jukzi** [comment]
Also happened on https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-github/job/PR-450/3/testReport/org.eclipse.jdt.debug.tests.variables/TestLogicalStructuresJava9/testMapLogicalStructure/

randomly failing since forever, see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569157

**Comment by jukzi** [comment]
again in https://download.eclipse.org/eclipse/downloads/drops4/I20250106-1800/testresults/html/org.eclipse.jdt.debug.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by SougandhS** [comment]
Happened again in https://download.eclipse.org/eclipse/downloads/drops4/I20250228-0140/testResults.php
