### ISSUE TITLE
Unsupported major.minor version 55.0

### ISSUE THREAD

**Issue by pepcim** [eclipse-jdt/eclipse.jdt.debug#319]
Hello,
I just installed Eclipse Version: 2022-03 (4.23.0)  // Build id: 20220310-1457
JAVa compile version(attached image): 1.7.80
When I try to debug I get following message:
Exception in thread "main" java.lang.UnsupportedClassVersionError: es/scsp/bo/services/emisores/especificos/SCDHPAJU/HAO_test : Unsupported major.minor version 55.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/135966517/13cbc327-ca60-4f8d-a694-dd6b77cd5283)

**Comment by iloveeclipse** [comment]
Please use JVM 11 to run your program, not Java 7.

**Comment by pepcim** [comment]
I need both, JAVA7 in order to compile the version I need.

**Comment by iloveeclipse** [comment]
Please use JVM 11 to **run** your program, not Java 7.
