### ISSUE TITLE
Test failure in org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#334]
https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/326

https://download.eclipse.org/eclipse/downloads/drops4/I20231026-1800/testresults/html/org.eclipse.jdt.debug.tests_ep430I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by akurtakov** [comment]
How is Mac configured to not fail on https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/Java21ElementTests.java ?

**Comment by iloveeclipse** [comment]
@akurtakov : please simply add a check for the Java version.
We need something like `org.eclipse.jdt.debug.testplugin.JavaProjectHelper.isJava19_Compatible()`

**Comment by iloveeclipse** [comment]
Alex, there is another problem **on Java 21**:

https://download.eclipse.org/eclipse/downloads/drops4/I20231027-0140/testresults/html/org.eclipse.jdt.debug.tests_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

```
Could not find launch configuration for Main2

junit.framework.AssertionFailedError: Could not find launch configuration for Main2
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.getLaunchConfiguration(AbstractDebugTest.java:1654)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.getLaunchConfiguration(AbstractDebugTest.java:1641)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1408)
at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testDefaultMainWithoutArgs(InstanceMainMethodsTests.java:53)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2722)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
```

and 

```
Failed to create the 'Two_One' test project. 'jp' is 'null' Stack tace: java.lang.NullPointerException: Cannot invoke "java.io.File.listFiles()" because "dir" is null at org.eclipse.jdt.debug.testplugin.JavaProjectHelper.addJavaFiles(JavaProjectHelper.java:624) at org.eclipse.jdt.debug.testplugin.JavaProjectHelper.importFilesFromDirectory(JavaProjectHelper.java:582) at org.eclipse.jdt.debug.tests.AbstractDebugTest.createProject(AbstractDebugTest.java:981) at org.eclipse.jdt.debug.tests.AbstractDebugTest.assert21Project(AbstractDebugTest.java:592) at org.eclipse.jdt.debug.tests.AbstractDebugTest.get21Project(AbstractDebugTest.java:910) at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.getProjectContext(InstanceMainMethodsTests.java:29) at org.eclipse.jdt.debug.tests.AbstractDebugTest.getLaunchConfiguration(AbstractDebugTest.java:1641) at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1408) at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testStaticMainWithoutArgs(InstanceMainMethodsTests.java:37) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at junit.framework.TestCase.runTest(TestCase.java:177) at junit.framework.TestCase.runBare(TestCase.java:142) at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2722) at junit.framework.TestResult$1.protect(TestResult.java:122) at junit.framework.TestResult.runProtected(TestResult.java:142) at junit.framework.TestResult.run(TestResult.java:125) at junit.framework.TestCase.run(TestCase.java:130) at junit.framework.TestSuite.runTest(TestSuite.java:241) at junit.framework.TestSuite.run(TestSuite.java:236) at junit.framework.TestSuite.runTest(TestSuite.java:241) at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61) at java.base/java.lang.Thread.run(Thread.java:1583)

junit.framework.AssertionFailedError: Failed to create the 'Two_One' test project.
'jp' is 'null'
Stack tace:
java.lang.NullPointerException: Cannot invoke "java.io.File.listFiles()" because "dir" is null
at org.eclipse.jdt.debug.testplugin.JavaProjectHelper.addJavaFiles(JavaProjectHelper.java:624)
at org.eclipse.jdt.debug.testplugin.JavaProjectHelper.importFilesFromDirectory(JavaProjectHelper.java:582)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.createProject(AbstractDebugTest.java:981)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.assert21Project(AbstractDebugTest.java:592)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.get21Project(AbstractDebugTest.java:910)
at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.getProjectContext(InstanceMainMethodsTests.java:29)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.getLaunchConfiguration(AbstractDebugTest.java:1641)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1408)
at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testStaticMainWithoutArgs(InstanceMainMethodsTests.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2722)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.handleProjectCreationException(AbstractDebugTest.java:762)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.assert21Project(AbstractDebugTest.java:610)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.get21Project(AbstractDebugTest.java:910)
at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.getProjectContext(InstanceMainMethodsTests.java:29)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.getLaunchConfiguration(AbstractDebugTest.java:1641)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndTerminate(AbstractDebugTest.java:1408)
at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testStaticMainWithoutArgs(InstanceMainMethodsTests.java:37)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2722)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by iloveeclipse** [comment]
@akurtakov:  `org.eclipse.jdt.debug.tests/build.properties` should include new `java21` folder. Sorry haven't immediately seen that.

**Comment by akurtakov** [comment]
Here it is https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/336

**Comment by akurtakov** [comment]
This one is fixed thus can be closed.
