### ISSUE TITLE
tests: silent IllegalStateException

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#395]
tests log exception but no test failed:
```
[2024-02-16T15:37:44.291Z] !ENTRY org.eclipse.jdt.debug.tests 1 0 2024-02-16 15:37:44.265
[2024-02-16T15:37:44.291Z] !MESSAGE [testListenersOnRuntimeError] setUp
[2024-02-16T15:37:44.545Z] 
[2024-02-16T15:37:44.545Z] !ENTRY org.eclipse.jface 4 4 2024-02-16 15:37:44.457
[2024-02-16T15:37:44.545Z] !MESSAGE Conditional Breakpoint Error : Conditional breakpoint encountered runtime exception.
[2024-02-16T15:37:44.545Z] 
[2024-02-16T15:37:44.545Z] Reason:
[2024-02-16T15:37:44.545Z] java.lang.StringIndexOutOfBoundsException
[2024-02-16T15:37:44.545Z] !STACK 0
[2024-02-16T15:37:44.545Z] java.lang.IllegalStateException: Error dialog is supposed to be shown now
[2024-02-16T15:37:44.545Z] 	at org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:339)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.jdt.internal.debug.ui.JavaDebugOptionsManager$1.run(JavaDebugOptionsManager.java:787)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.jdt.debug.tests.DebugSuite.run(DebugSuite.java:77)
[2024-02-16T15:37:44.545Z] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
[2024-02-16T15:37:44.545Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-02-16T15:37:44.545Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
[2024-02-16T15:37:44.545Z] 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:42)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:34)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:129)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:44)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
[2024-02-16T15:37:44.545Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-02-16T15:37:44.545Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
[2024-02-16T15:37:44.545Z] 	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
[2024-02-16T15:37:44.545Z] !SUBENTRY 1 org.eclipse.jdt.debug.ui 4 4 2024-02-16 15:37:44.458
[2024-02-16T15:37:44.545Z] !MESSAGE java.lang.StringIndexOutOfBoundsException
[2024-02-16T15:37:45.109Z] 
[2024-02-16T15:37:45.109Z] !ENTRY org.eclipse.jdt.debug.tests 1 0 2024-02-16 15:37:45.050
[2024-02-16T15:37:45.109Z] !MESSAGE [testListenersOnRuntimeError] tearDown

```

**Comment by jukzi** [comment]
that IllegalStateException was introduced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=567712
