### ISSUE TITLE
Lot's of `com.sun.jdi.ObjectCollectedException` in Eclipse log

### ISSUE THREAD

**Issue by guw** [eclipse-jdt/eclipse.jdt.debug#413]
A user is seeing lots of the following excepgtions in the log.

It's unclear whether this is a problem or not. Can it be fixed? It something wrong that we need to fix?
Maybe the log message needs some additional enhancements?

```
!ENTRY org.eclipse.jdt.debug 4 125 2024-03-19 17:29:35.150
!MESSAGE Internal error logged from JDI Debug: 
!STACK 0
com.sun.jdi.ObjectCollectedException
	at org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(MirrorImpl.java:295)
	at org.eclipse.jdi.internal.ObjectReferenceImpl.disableCollection(ObjectReferenceImpl.java:104)
	at org.eclipse.jdt.internal.debug.core.model.JDIObjectValue.disableCollection(JDIObjectValue.java:622)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.disableCollection(Interpreter.java:121)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.push(Interpreter.java:106)
	at org.eclipse.jdt.internal.debug.eval.ast.instructions.Instruction.push(Instruction.java:104)
	at org.eclipse.jdt.internal.debug.eval.ast.instructions.PushThis.execute(PushThis.java:56)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.execute(Interpreter.java:69)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable$1EvaluationRunnable.run(ASTEvaluationEngine.java:843)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.runEvaluation(JDIThread.java:821)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run(ASTEvaluationEngine.java:896)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run(JDIThread.java:3481)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by SougandhS** [comment]
Hi @guw 
Could you please provide a reproducer for this ?

**Comment by guw** [comment]
This is too long ago. Sorry.
