### ISSUE TITLE
Random failing OpenFromClipboardTests.testMethod_11

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#442]
on mac:
https://download.eclipse.org/eclipse/downloads/drops4/I20240514-1800/testresults/html/org.eclipse.jdt.debug.tests_ep432I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMethod_11(OpenFromClipboardTests.java:456)
```

similar fails had been on win and linux: https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/28

**Comment by SougandhS** [comment]
This is not failing anymore
