### ISSUE TITLE
Random failing TypeNameBreakpointTests.testWildCardClassPrepareBreakpoint

### ISSUE THREAD

**Issue by SougandhS** [eclipse-jdt/eclipse.jdt.debug#479]
Unit test failed -
Stack - 
org.eclipse.jdt.debug.tests.breakpoints.TypeNameBreakpointTests()

expected:<HitCountLooper> but was:<null>

junit.framework.ComparisonFailure: expected:<HitCountLooper> but was:<null>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at junit.framework.TestCase.assertEquals(TestCase.java:260)
at org.eclipse.jdt.debug.tests.breakpoints.TypeNameBreakpointTests.testWildCardClassPrepareBreakpoint(TypeNameBreakpointTests.java:503)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2768)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)

<img width="1723" alt="image" src="https://github.com/user-attachments/assets/4e044149-1a5b-4533-af80-6572afe6e1cf">

**Comment by jukzi** [comment]
only random failing
https://download.eclipse.org/eclipse/downloads/drops4/I20240828-1820/testresults/html/org.eclipse.jdt.debug.tests_ep433I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
