### ISSUE TITLE
[23] Debug tests are failing with JVM 23

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.debug#483]
Many tests in jdt.debug test suite are failing when run with JVM 23 on the BETA_JAVA23 branch, for e.g., org.eclipse.debug.jdi.tests.AccessibleTest.testJDIIsPublic().
The error trace is:

```
java.lang.Error: Could not contact the VM
	at org.eclipse.debug.jdi.tests.AbstractJDITest.connectToVM(AbstractJDITest.java:928)
	at org.eclipse.debug.jdi.tests.AbstractJDITest.launchTargetAndConnectToVM(AbstractJDITest.java:662)
	at org.eclipse.debug.jdi.tests.AbstractJDITest.launchTargetAndStartProgram(AbstractJDITest.java:1117)
	at org.eclipse.debug.jdi.tests.AbstractJDITest.setUp(AbstractJDITest.java:1126)
```

**Comment by jarthana** [comment]
I will take this up via https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/482 itself

**Comment by mpalat** [comment]
@jarthana I believe this is done?

**Comment by jarthana** [comment]
Yes, closing now.
