### ISSUE TITLE
Random failed JavaStackTraceAmbiguityTest.testLinkNavigationTrueForSingleParameter

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#529]
"StackTest\src\a\Sample.java" could not be deleted

```
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:816)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:365)
	at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForSingleParameter(JavaStackTraceAmbiguityTest.java:83)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2773)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Contains: Could not delete '/StackTest/src'.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:416)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:363)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:398)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:855)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1834)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:803)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:365)
	at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForSingleParameter(JavaStackTraceAmbiguityTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2773)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Contains: Problems encountered while deleting files.
Contains: Problems encountered while deleting files.
Contains: Could not delete: C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17\workarea\I20241008-1810\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\a\Sample.java.
java.nio.file.FileSystemException: C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17\workarea\I20241008-1810\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\a\Sample.java: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:308)
	at org.eclipse.core.internal.filesystem.local.LocalFile.lambda$2(LocalFile.java:325)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:979)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:335)
	at org.eclipse.core.internal.filesystem.local.LocalFile.lambda$2(LocalFile.java:325)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Contains: OK
Contains: OK
Contains: OK
Contains: OK
Contains: Could not delete 'C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17\workarea\I20241008-1810\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest'.

```
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep434I-unit-win32-java17/53/testReport/junit/org.eclipse.jdt.debug.tests.console/JavaStackTraceAmbiguityTest/testLinkNavigationTrueForSingleParameter/

**Comment by trancexpress** [comment]
Seen also here:

https://download.eclipse.org/eclipse/downloads/drops4/I20260225-1800/reports.html#tests

https://download.eclipse.org/eclipse/downloads/drops4/I20260225-1800/testresults/html/org.eclipse.jdt.debug.tests_ep439I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html

```
org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest	testLinkNavigationTrueForSingleVarArgs	Error	Problems encountered while deleting resources.

org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:839)
at org.eclipse.core.internal.resources.Project.delete(Project.java:378)
at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForSingleVarArgs(JavaStackTraceAmbiguityTest.java:218)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2926)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
Contains: Could not delete '/StackTest/src'.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:434)
at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:373)
at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:409)
at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:873)
at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1922)
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:826)
at org.eclipse.core.internal.resources.Project.delete(Project.java:378)
at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForSingleVarArgs(JavaStackTraceAmbiguityTest.java:218)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2926)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
Contains: Problems encountered while deleting files.
Contains: OK
Contains: OK
Contains: Problems encountered while deleting files.
Contains: OK
Contains: Could not delete: C:\Users\genie.releng\workspace\AutomatedTests\ep439I-unit-win32-x86_64-java21\workarea\I20260225-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\c\Sample.java.
java.nio.file.FileSystemException: C:\Users\genie.releng\workspace\AutomatedTests\ep439I-unit-win32-x86_64-java21\workarea\I20260225-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\c\Sample.java: The process cannot access the file because it is being used by another process
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:312)
at org.eclipse.core.internal.filesystem.local.LocalFile.lambda$3(LocalFile.java:335)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:991)
at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:345)
at org.eclipse.core.internal.filesystem.local.LocalFile.lambda$3(LocalFile.java:335)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Contains: OK
Contains: OK
Contains: OK
Contains: Could not delete 'C:\Users\genie.releng\workspace\AutomatedTests\ep439I-unit-win32-x86_64-java21\workarea\I20260225-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest'.
```

**Comment by trancexpress** [comment]
> No, JDT indexer. I guess the test doesn't wait for it.

Shouldn't that result in logged exceptions? The Java error is for another process:

```
java.nio.file.FileSystemException: C:\Users\genie.releng\workspace\AutomatedTests\ep439I-unit-win32-x86_64-java21\workarea\I20260225-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\c\Sample.java: The process cannot access the file because it is being used by another process
```

**Comment by iloveeclipse** [comment]
I'm not sure the generic message is correct. I believe it wants to say "you delete something someone has open somewhere". So if JDT indexer reads he file while we are deleting test project, delete fails on Windows.

**Comment by SougandhS** [comment]
Got similar failure again 

https://download.eclipse.org/eclipse/downloads/drops4/I20260410-1800/testresults/html/org.eclipse.jdt.debug.tests_ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html

Problems encountered while deleting resources.

```
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:839)
at org.eclipse.core.internal.resources.Project.delete(Project.java:378)
at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForGenerics(JavaStackTraceAmbiguityTest.java:272)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2993)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
Contains: Could not delete '/StackTest/src'.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:440)
at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:373)
at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:409)
at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:873)
at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1922)
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:826)
at org.eclipse.core.internal.resources.Project.delete(Project.java:378)
at org.eclipse.jdt.debug.tests.console.JavaStackTraceAmbiguityTest.testLinkNavigationTrueForGenerics(JavaStackTraceAmbiguityTest.java:272)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2993)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583)
Contains: Problems encountered while deleting files.
Contains: OK
Contains: OK
Contains: OK
Contains: OK
Contains: OK
Contains: Could not delete: C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\workarea\I20260410-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\SampleGenerics.java.
java.nio.file.FileSystemException: C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\workarea\I20260410-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest\src\SampleGenerics.java: The process cannot access the file because it is being used by another process
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:312)
at org.eclipse.core.internal.filesystem.local.LocalFile.lambda$3(LocalFile.java:335)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Contains: Could not delete 'C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\workarea\I20260410-1800\eclipse-testing\test-eclipse\eclipse\jdt_folder\StackTest'.
```
