### ISSUE TITLE
3 Test failures for I20241014-0530 build on Windows

### ISSUE THREAD

**Issue by SougandhS** [eclipse-jdt/eclipse.jdt.debug#537]
Unit test results -> https://download.eclipse.org/eclipse/downloads/drops4/I20241014-0530/testresults/html/org.eclipse.jdt.debug.tests_ep434I-unit-win32-java17_win32.win32.x86_64_17.html

1 . org.eclipse.jdt.debug.tests.breakpoints.WatchpointTests.testFinalWatchpoint

ERROR
Program did not suspend, launch terminated.
org.eclipse.jdt.debug.tests.AbstractDebugTest$TestAgainException: Program did not suspend, launch terminated.at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1310)at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1260)at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToBreakpoint(AbstractDebugTest.java:1450)at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToBreakpoint(AbstractDebugTest.java:1405)at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToBreakpoint(AbstractDebugTest.java:1377)at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToBreakpoint(AbstractDebugTest.java:1364)at org.eclipse.jdt.debug.tests.breakpoints.WatchpointTests.testFinalWatchpoint(WatchpointTests.java:305)at java.base/java.lang.reflect.Method.invoke(Method.java:568)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2786)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:833)

2. org.eclipse.jdt.debug.tests.breakpoints.TriggerPointBreakpointsTests.testTriggerPointBreakpoint

ERROR
Program did not suspend, launch terminated.
org.eclipse.jdt.debug.tests.AbstractDebugTest$TestAgainException: Program did not suspend, launch terminated.
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1310)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait(AbstractDebugTest.java:1260)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToLineBreakpoint(AbstractDebugTest.java:1548)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToLineBreakpoint(AbstractDebugTest.java:1531)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.launchToLineBreakpoint(AbstractDebugTest.java:1515)
at org.eclipse.jdt.debug.tests.breakpoints.TriggerPointBreakpointsTests.testTriggerPointBreakpoint(TriggerPointBreakpointsTests.java:46)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2786)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:833)

3. org.eclipse.jdt.debug.tests.ui.DebugHoverTests. testBug573547_insideLambda_onOuterScopeVariable_whileOnPreviousFrame

Failure
After waiting 10000ms the editor selection was not moved to the expected line expected:<39> but was:<40>

junit.framework.AssertionFailedError: After waiting 10000ms the editor selection was not moved to the expected line expected:<39> but was:<40>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.debug.tests.ui.DebugHoverTests.selectFrame(DebugHoverTests.java:1484)
at org.eclipse.jdt.debug.tests.ui.DebugHoverTests.testBug573547_insideLambda_onOuterScopeVariable_whileOnPreviousFrame(DebugHoverTests.java:1246)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2773)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SougandhS** [comment]
Test 1 & 2 passed on IBuild [[I20241015-1820](https://download.eclipse.org/eclipse/downloads/drops4/I20241015-1820/testResults.php)] 
Test 3 - Regression 
Will close this issue and raise for Regression

**Comment by akurtakov** [comment]
Was there anything done to fix the test? If not it's quite likely that this is unstable test that will fail soon again.

**Comment by SougandhS** [comment]
No fix were done for 1 & 2, but those are also new.
1 fix was done for 3rd one (Regression) but still its coming up.
