### ISSUE TITLE
[Test] testHyperLink throws NPE on MacOS in I20241111-1800 & I20241110-1800

### ISSUE THREAD

**Issue by SougandhS** [eclipse-jdt/eclipse.jdt.debug#559]
org.eclipse.jdt.debug.tests.core.LineTrackerTests.testHyperLink throws Null pointer exception
<img width="640" alt="image" src="https://github.com/user-attachments/assets/bb8ef303-fc18-4153-aabe-273636908263">

Cannot invoke "org.eclipse.debug.ui.console.IConsole.getDocument()" because "org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.fConsole" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.debug.ui.console.IConsole.getDocument()" because "org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.fConsole" is null
at org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.getDocument(ConsoleLineTracker.java:67)
at org.eclipse.jdt.debug.tests.core.LineTrackerTests.testHyperLink(LineTrackerTests.java:184)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2774)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by trancexpress** [comment]
Failed again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260606-1800/testresults/html/org.eclipse.jdt.debug.tests_ep441I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

```
	Cannot invoke "org.eclipse.debug.ui.console.IConsole.getDocument()" because "org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.fConsole" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.debug.ui.console.IConsole.getDocument()" because "org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.fConsole" is null
at org.eclipse.jdt.debug.testplugin.ConsoleLineTracker.getDocument(ConsoleLineTracker.java:67)
at org.eclipse.jdt.debug.tests.core.LineTrackerTests.testHyperLink(LineTrackerTests.java:186)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:3001)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583) 
```

Lets try something simple, which builds on top of previous attempts to fix sporadic fails: https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/962

**Comment by SougandhS** [comment]
Test is not failing after https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/962 🎉
\- Closing this now
