### ISSUE TITLE
SWT "Invalid thread access" during debug

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#563]
```
eclipse.buildId=4.34.0.I20241113-1800
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.jdt.debug
Error
Fri Nov 15 15:23:47 CET 2024
Exception occurred while notifying listener: JavaLineBreakpoint on [marker=Marker [on: /hibernate/maven/hibernate-jpamodelgen-6.6.2.Final.jar, id: 2161169, type: org.eclipse.jdt.debug.javaLineBreakpointMarker, attributes: [charEnd: 4625, charStart: 4578, lineNumber: 104, message: Line breakpoint:ProcessorSessionFactory [line: 104] - ProcessorSessionFactory(ProcessingEnvironment, Map<String, String>, Map<String, Set<String>>), org.eclipse.debug.core.enabled: true, org.eclipse.debug.core.id: org.eclipse.jdt.debug, org.eclipse.jdt.debug.core.installCount: 1, org.eclipse.jdt.debug.core.suspendPolicy: 2, org.eclipse.jdt.debug.core.typeName: org.hibernate.processor.validation.ProcessorSessionFactory, org.eclipse.jdt.debug.ui.JAVA_ELEMENT_HANDLE_ID: =hibernate/maven\/hibernate-jpamodelgen-6.6.2.Final.jar=/module=/true=/<org.hibernate.processor.validation(ProcessorSessionFactory.class[ProcessorSessionFactory, org.eclipse.jdt.internal.core.JavaModelManager.handleId: =hibernate/maven\/hibernate-jpamodelgen-6.6.2.Final.jar=/module=/true=/<org.hibernate.processor.validation(ProcessorSessionFactory.class], created: 15.11.24, 15:22]], with event: ClassPrepareEvent: 25 referenceType=org.hibernate.processor.validation.ProcessorSessionFactory$ByteBuddy$gHcoemPf

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Display.error(Display.java:1324)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:875)
	at org.eclipse.swt.widgets.Display.getShells(Display.java:2318)
	at org.eclipse.ui.internal.progress.ProgressManagerUtil.getModalShellExcluding(ProgressManagerUtil.java:410)
	at org.eclipse.ui.internal.progress.ProgressManagerUtil.getDefaultParent(ProgressManagerUtil.java:464)
	at org.eclipse.jdt.internal.debug.ui.NoLineNumberAttributesStatusHandler.handleStatus(NoLineNumberAttributesStatusHandler.java:36)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaLineBreakpoint.determineLocations(JavaLineBreakpoint.java:403)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaLineBreakpoint.newRequests(JavaLineBreakpoint.java:292)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.createRequest(JavaBreakpoint.java:517)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleClassPrepareEvent(JavaBreakpoint.java:382)
	at org.eclipse.jdt.internal.debug.core.breakpoints.JavaBreakpoint.handleEvent(JavaBreakpoint.java:304)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher.dispatch(EventDispatcher.java:159)
	at org.eclipse.jdt.internal.debug.core.EventDispatcher.run(EventDispatcher.java:320)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

@iloveeclipse may that relate to 353005075c1ab3df53959b3deee9299cfbb7d934 in the stacktrace?

**Comment by iloveeclipse** [comment]
Yes, it does. Any steps to reproduce?
Fix: https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/564

**Comment by jukzi** [comment]
> Any steps to reproduce?

Put a breakpoint in an instrumented class. I don't know a minimal reproducer, but i will test your PR in exactly my situation.

**Comment by jukzi** [comment]
Minimal reproducer: add breakpoint in any Hello-world and disable line number information:
![image](https://github.com/user-attachments/assets/932558f9-6bd3-4d68-a380-ddde6821fcab)
then launch hello world in debug mode.
