### ISSUE TITLE
 [19] testLimitModulesTest might fail with Java 19

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#65]
Package dependency change might need a change for Debug test.

**Comment by SarikaSinha** [comment]
Failing for 19:
https://download.eclipse.org/eclipse/downloads/drops4/Y20220613-0600/testresults/html/org.eclipse.jdt.debug.tests_ep425Y-unit-cen64-gtk3-java19_linux.gtk.x86_64_19.html


org.eclipse.jdt.debug.tests.core.ModuleOptionsTests | testLimitModules1 | Failure | Unknown set of default modules java.se,jdk.accessibility,jdk.attach,jdk.compiler,jdk.dynalink,jdk.httpserver,jdk.incubator.concurrent,jdk.incubator.vector,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management,jdk.management.jfr,jdk.net,jdk.nio.mapmode,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.domjunit.framework.AssertionFailedError: Unknown set of default modules java.se,jdk.accessibility,jdk.attach,jdk.compiler,jdk.dynalink,jdk.httpserver,jdk.incubator.concurrent,jdk.incubator.vector,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management,jdk.management.jfr,jdk.net,jdk.nio.mapmode,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.domat junit.framework.Assert.fail(Assert.java:57)at junit.framework.TestCase.fail(TestCase.java:223)at org.eclipse.jdt.debug.tests.core.ModuleOptionsTests.testLimitModules1(ModuleOptionsTests.java:269)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:578)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2670)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:1596)
-- | -- | -- | --



Last change was for Java 16
[Bug 568295](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568295) - [16] testLimitModulesTest might fail with Java 16
