### ISSUE TITLE
NPE on clicking link in console to missing resource

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#9]
Open Java Stack Trace Console, paste snippet below and try to click on `DispatchingTest.java`.
Note: org.eclipse.equinox.http.servlet.tests project should not exist in the workspace.

```
org.junit.ComparisonFailure: expected:<foo=ba[z]> but was:<foo=ba[r]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.equinox.http.servlet.tests.DispatchingTest.test_headers_forward(DispatchingTest.java:1411)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

Result: NPE below.

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.debug.ui.console.JavaStackTraceHyperlink$1.run(JavaStackTraceHyperlink.java:131)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This is a regression from #5

**Comment by SarikaSinha** [comment]
if (((List<?>) result).isEmpty()) {
	result = null;
}
else if (((List<?>) result).size() == 1) {
	result = ((List<?>) result).get(0);
}
Will this not be sufficient? @iloveeclipse

**Comment by iloveeclipse** [comment]
> if (((List) result).isEmpty()) { result = null; } else if (((List) result).size() == 1) { result = ((List<?>) result).get(0); } Will this not be sufficient? @iloveeclipse

Yes, but all the casts look not nice :-)

**Comment by iloveeclipse** [comment]
Verified fix with I20220405-0600
